## Using Vectorised Operation

In [61]:
import numpy as np
import time

In [62]:
# lets create two arrays consisting of some of random variable between 0 and 1
a = np.random.rand(1000000)
b = np.random.rand(1000000)

In [63]:
## printing first 10 values of array
print(a[:10])
print(b[:10])

[0.31603287 0.35668028 0.53658804 0.63797001 0.69250502 0.54974012
 0.97937568 0.97598816 0.9424275  0.90875343]
[0.61817442 0.92878612 0.61383257 0.40816786 0.96380162 0.40830434
 0.35927901 0.25265724 0.67216418 0.21847864]


# calculating the sum of all numbers in the list


In [64]:
start = time.time()

total = 0
for i in a:
    total = total + i
    
stop = time.time()

print("Using For Loop:" +str(1000*(stop - start)) + "ms")
print(total)

Using For Loop:807.8389167785645ms
499512.9220743456


In [65]:
## sum vector
one = np.ones(1000000)


In [66]:
# using vertorised operation 

start = time.time()
total = np.matmul(np.transpose(one) , a)

stop = time.time()

print("vectorised version : " +str(1000*(stop - start)) + "ms")
print(total)

vectorised version : 4.985570907592773ms
499512.9220743697


In [67]:
## using inbuilt function of python
start = time.time()
total = sum(a)
stop = time.time()

print("vectorised version : " +str(1000*(stop - start)) + "ms")
print(total)

vectorised version : 168.54500770568848ms
499512.9220743456


In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math 
import os

In [32]:
## for linear regression using stat model package
import statsmodels.api as stm
import math

In [26]:
cars = pd.read_csv("cars.csv")

In [27]:
cars.head()

Car   MPG  Cylinders  Displacement  Horsepower  \
0  Chevrolet Chevelle Malibu  18.0          8         307.0         130   
1          Buick Skylark 320  15.0          8         350.0         165   
2         Plymouth Satellite  18.0          8         318.0         150   
3              AMC Rebel SST  16.0          8         304.0         150   
4                Ford Torino  17.0          8         302.0         140   

   Weight  Acceleration  Model Origin  
0    3504          12.0     70     US  
1    3693          11.5     70     US  
2    3436          11.0     70     US  
3    3433          12.0     70     US  
4    3449          10.5     70     US

In [28]:
cars2 = cars.loc[(cars.MPG != 0 ) & (cars.Horsepower != 0),]

In [29]:
cars2.shape

(392, 9)

In [33]:
X = cars2[["Weight" ,"Acceleration" ,"Horsepower" ]]
X = stm.add_constant(X)
y = cars2.MPG

In [37]:
X.head()

const  Weight  Acceleration  Horsepower
0    1.0    3504          12.0         130
1    1.0    3693          11.5         165
2    1.0    3436          11.0         150
3    1.0    3433          12.0         150
4    1.0    3449          10.5         140

In [38]:
y.head()

0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
Name: MPG, dtype: float64

## Linear Regression Statsmodels Solution

In [40]:
model = stm.OLS(y , X).fit()
model.params

const           45.678293
Weight          -0.005789
Acceleration    -0.002066
Horsepower      -0.047496
dtype: float64

# Linear Regression Statsmodels Solution¶ - Using Matrix

In [43]:
## CONVERTIN DATA FRAME INTO MATRIX

X = np.matrix(X)
y = np.matrix(y)

In [45]:
X.shape

(392, 4)

In [50]:
X

matrix([[1.000e+00, 3.504e+03, 1.200e+01, 1.300e+02],
        [1.000e+00, 3.693e+03, 1.150e+01, 1.650e+02],
        [1.000e+00, 3.436e+03, 1.100e+01, 1.500e+02],
        ...,
        [1.000e+00, 2.295e+03, 1.160e+01, 8.400e+01],
        [1.000e+00, 2.625e+03, 1.860e+01, 7.900e+01],
        [1.000e+00, 2.720e+03, 1.940e+01, 8.200e+01]])

In [46]:
y.shape

(1, 392)

In [48]:
## transpose
tx = np.transpose(X)
tx

matrix([[1.000e+00, 1.000e+00, 1.000e+00, ..., 1.000e+00, 1.000e+00,
         1.000e+00],
        [3.504e+03, 3.693e+03, 3.436e+03, ..., 2.295e+03, 2.625e+03,
         2.720e+03],
        [1.200e+01, 1.150e+01, 1.100e+01, ..., 1.160e+01, 1.860e+01,
         1.940e+01],
        [1.300e+02, 1.650e+02, 1.500e+02, ..., 8.400e+01, 7.900e+01,
         8.200e+01]])

In [ ]:
## closed from solution for the coefficients

In [54]:
(np.linalg.inv(np.matmul(tx ,X)) ,tx)

(matrix([[ 3.21828758e-01,  2.19957681e-05, -1.55585778e-02,
          -1.36854493e-03],
         [ 2.19957681e-05,  1.85062876e-08, -1.94258251e-06,
          -4.49026162e-07],
         [-1.55585778e-02, -1.94258251e-06,  8.43933285e-04,
           7.87497484e-05],
         [-1.36854493e-03, -4.49026162e-07,  7.87497484e-05,
           1.41829354e-05]]),
 matrix([[1.000e+00, 1.000e+00, 1.000e+00, ..., 1.000e+00, 1.000e+00,
          1.000e+00],
         [3.504e+03, 3.693e+03, 3.436e+03, ..., 2.295e+03, 2.625e+03,
          2.720e+03],
         [1.200e+01, 1.150e+01, 1.100e+01, ..., 1.160e+01, 1.860e+01,
          1.940e+01],
         [1.300e+02, 1.650e+02, 1.500e+02, ..., 8.400e+01, 7.900e+01,
          8.200e+01]]))

### b = inv(Htrans.H)* Htans*y

In [59]:
np.matmul(np.matmul(np.linalg.inv(np.matmul(tx , X)) ,tx), np.transpose(y))

matrix([[ 4.56782929e+01],
        [-5.78940259e-03],
        [-2.06565785e-03],
        [-4.74956153e-02]])

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X, y)
reg.score(X, y)
1.0
reg.coef_
array([1., 2.])
reg.intercept_
3.0000...
reg.predict(np.array([[3, 5]]))
array([16.])