In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt
import statsmodels.api as stm
import math

In [2]:
df = pd.read_excel("D:\Desktop\DAILY RECORDS.xlsx")

In [3]:
df.shape

(47, 13)

In [4]:
## Importing Data set 

## Data Exploration 
#### This data consist of my real time activity of what i did daily for 47 days all entered entries are in hours and for each row sum of total is 24 


##### Data does not have any null value as i have recorded daily so data is clean n you can process further

In [5]:
df.head()

DAY        DATE  CLASSROOM   STUDY/\nASSIGNMENT\n  SLEEP \nACTUAL  \
0     Monday 2020-09-07         4.0                   6.0             8.5   
1    Tuesday 2020-09-08         6.5                   4.5             6.0   
2  Wednesday 2020-09-09         4.0                   4.5             9.0   
3   Thursday 2020-09-10         6.5                   5.0             9.0   
4     Friday 2020-09-11         4.0                   4.5             7.0   

   SLEEP \nTHINKING  FITNESS/\nFOOTBALL  REMAINING\n TIME  \
0               2.0                 0.0              3.00   
1               2.0                 1.5              3.00   
2               0.5                 0.0              4.50   
3               0.5                 0.0              2.25   
4               1.5                 1.0              3.00   

   DIGITAL\n INTERACTION  SOCIAL\nINTERACTION  MOVIES/TV  TRAVEL\nOUTGOING  \
0                   0.50                  0.0        0.0               0.0   
1                   0.50                  0.0        0.0               0.0   
2                   1.50                  0.0        0.0               0.0   
3                   0.75                  0.0        0.0               0.0   
4                   1.00                  2.0        0.0               0.0   

   productive\n Day out \nof of 10   
0                               8.5  
1                               8.0  
2                               8.0  
3                               8.0  
4                               7.5

In [7]:
df = df[['DAY ', 'DATE', 'CLASSROOM ', 'STUDY/\nASSIGNMENT\n', 'SLEEP \nACTUAL',
       'SLEEP \nTHINKING', 'FITNESS/\nFOOTBALL',
       'DIGITAL\n INTERACTION', 'SOCIAL\nINTERACTION', 'MOVIES/TV',
       'TRAVEL\nOUTGOING', 'productive\n Day out \nof of 10 ']]

In [8]:
df2 = df[df.columns[2:]] 

In [10]:
from scipy.stats import zscore   ## importing library
df_std = df2.apply(zscore)  

### storing into pd dataframe

In [11]:
df_std.head()

CLASSROOM   STUDY/\nASSIGNMENT\n  SLEEP \nACTUAL  SLEEP \nTHINKING  \
0   -0.015981              1.257465        0.451206          1.347289   
1    1.057056              0.321831       -1.476675          1.347289   
2   -0.015981              0.321831        0.836783         -0.997992   
3    1.057056              0.633709        0.836783         -0.997992   
4   -0.015981              0.321831       -0.705523          0.565529   

   FITNESS/\nFOOTBALL  DIGITAL\n INTERACTION  SOCIAL\nINTERACTION  MOVIES/TV  \
0           -0.691109              -1.081992            -0.475670  -0.418471   
1            1.064682              -1.081992            -0.475670  -0.418471   
2           -0.691109               0.034443            -0.475670  -0.418471   
3           -0.691109              -0.802883            -0.475670  -0.418471   
4            0.479418              -0.523774             3.412414  -0.418471   

   TRAVEL\nOUTGOING  productive\n Day out \nof of 10   
0         -0.182361                          1.273061  
1         -0.182361                          0.692150  
2         -0.182361                          0.692150  
3         -0.182361                          0.692150  
4         -0.182361                          0.111238

In [12]:
df_std.columns

Index(['CLASSROOM ', 'STUDY/\nASSIGNMENT\n', 'SLEEP \nACTUAL',
       'SLEEP \nTHINKING', 'FITNESS/\nFOOTBALL', 'DIGITAL\n INTERACTION',
       'SOCIAL\nINTERACTION', 'MOVIES/TV', 'TRAVEL\nOUTGOING',
       'productive\n Day out \nof of 10 '],
      dtype='object')

In [13]:
scaler = preprocessing.StandardScaler()

# Fit your data on the scaler object
scaled_df = scaler.fit_transform(df2)

### standardizing and storing into array 

In [14]:
scaled_df

array([[-0.0159814 ,  1.25746489,  0.45120635,  1.34728944, -0.69110939,
        -1.081992  , -0.4756698 , -0.41847129, -0.18236118,  1.27306103],
       [ 1.05705559,  0.32183138, -1.47667533,  1.34728944,  1.06468204,
        -1.081992  , -0.4756698 , -0.41847129, -0.18236118,  0.69214969],
       [-0.0159814 ,  0.32183138,  0.83678269, -0.99799217, -0.69110939,
         0.03444321, -0.4756698 , -0.41847129, -0.18236118,  0.69214969],
       [ 1.05705559,  0.63370922,  0.83678269, -0.99799217, -0.69110939,
        -0.8028832 , -0.4756698 , -0.41847129, -0.18236118,  0.69214969],
       [-0.0159814 ,  0.32183138, -0.70552266,  0.5655289 ,  0.47941823,
        -0.52377439,  3.41241381, -0.41847129, -0.18236118,  0.11123834],
       [-0.0159814 , -0.61380212,  0.83678269, -0.99799217,  1.64994584,
         0.59266082,  0.4963511 , -0.41847129, -0.18236118, -0.469673  ],
       [-1.73284058, -1.23755779,  0.06563001, -1.38887244,  2.23520965,
         1.70909604,  0.4963511 ,  4.24854751

## Now solvingLinear regression from Scratch 

## setting target variable and predictors and also adding constant variable for getting value of bo

In [16]:
x_target = df_std[['CLASSROOM ', 'STUDY/\nASSIGNMENT\n',
       'SLEEP \nTHINKING', 'FITNESS/\nFOOTBALL',
       'DIGITAL\n INTERACTION', 'SOCIAL\nINTERACTION',
        ]]
x_target = stm.add_constant(x_target)

In [17]:
x_target.head()

const  CLASSROOM   STUDY/\nASSIGNMENT\n  SLEEP \nTHINKING  \
0    1.0   -0.015981              1.257465          1.347289   
1    1.0    1.057056              0.321831          1.347289   
2    1.0   -0.015981              0.321831         -0.997992   
3    1.0    1.057056              0.633709         -0.997992   
4    1.0   -0.015981              0.321831          0.565529   

   FITNESS/\nFOOTBALL  DIGITAL\n INTERACTION  SOCIAL\nINTERACTION  
0           -0.691109              -1.081992            -0.475670  
1            1.064682              -1.081992            -0.475670  
2           -0.691109               0.034443            -0.475670  
3           -0.691109              -0.802883            -0.475670  
4            0.479418              -0.523774             3.412414

In [18]:
y = df_std[["SLEEP \nACTUAL"]]
y.head()

SLEEP \nACTUAL
0        0.451206
1       -1.476675
2        0.836783
3        0.836783
4       -0.705523

# b = inv(Htrans.H)* Htans*y

# H is predictors 
# y is target

In [19]:
X = np.matrix(x_target)
y = np.matrix(y)

In [20]:
print(X.shape)
print(y.shape)

(47, 7)
(47, 1)


In [21]:
tx = np.transpose(X)


In [22]:
# Htrans*H

br = np.matmul(tx , X)


In [23]:
br

matrix([[ 4.70000000e+01, -7.99360578e-15,  3.99680289e-15,
         -1.63757896e-15,  6.66133815e-16, -2.88657986e-15,
          6.66133815e-16],
        [-7.99360578e-15,  4.70000000e+01,  4.65920105e+00,
         -1.25293254e+00, -2.65187123e+01, -1.60869098e+01,
          3.39756387e+00],
        [ 3.99680289e-15,  4.65920105e+00,  4.70000000e+01,
         -6.30284567e-01, -1.46898465e+01, -1.91666400e+01,
         -1.16003929e+01],
        [-1.63757896e-15, -1.25293254e+00, -6.30284567e-01,
          4.70000000e+01,  6.81680189e+00,  1.87741623e+00,
         -6.54796747e-01],
        [ 6.66133815e-16, -2.65187123e+01, -1.46898465e+01,
          6.81680189e+00,  4.70000000e+01,  7.83256814e+00,
         -1.22855742e+00],
        [-2.88657986e-15, -1.60869098e+01, -1.91666400e+01,
          1.87741623e+00,  7.83256814e+00,  4.70000000e+01,
          4.02562416e+00],
        [ 6.66133815e-16,  3.39756387e+00, -1.16003929e+01,
         -6.54796747e-01, -1.22855742e+00,  4.02562416e+00

In [24]:
inv_br = (np.linalg.inv(br))

In [25]:
inv_br

matrix([[ 2.12765957e-02,  6.00880999e-18, -8.56224018e-19,
          4.35925293e-19,  2.27673320e-18,  2.71281708e-18,
         -1.11402452e-18],
        [ 6.00880999e-18,  3.69439098e-02,  7.79495263e-03,
         -2.55026124e-03,  2.15433471e-02,  1.24454845e-02,
         -1.28506994e-03],
        [-8.56224018e-19,  7.79495263e-03,  3.11484025e-02,
         -1.59614669e-03,  1.23928572e-02,  1.28268808e-02,
          6.32752853e-03],
        [ 4.35925293e-19, -2.55026124e-03, -1.59614669e-03,
          2.19564808e-02, -4.85269547e-03, -1.60127874e-03,
          1.06598093e-04],
        [ 2.27673320e-18,  2.15433471e-02,  1.23928572e-02,
         -4.85269547e-03,  3.70088830e-02,  6.29436506e-03,
          1.86209309e-03],
        [ 2.71281708e-18,  1.24454845e-02,  1.28268808e-02,
         -1.60127874e-03,  6.29436506e-03,  2.97944784e-02,
         -1.43497164e-04],
        [-1.11402452e-18, -1.28506994e-03,  6.32752853e-03,
          1.06598093e-04,  1.86209309e-03, -1.43497164e-04

In [26]:
br2 = np.matmul(tx , y)

## Final multiplication predicting values of b0 , b1 , b2 , b3.........bn

In [27]:
final_matrix = np.matmul(inv_br , br2)

### so finally we got 8 values which are b0 , b1 , b2 , b3 ......b7 without using any library 

In [28]:
final_matrix

matrix([[-3.45655583e-16],
        [-5.45402375e-01],
        [-9.97800910e-02],
        [-2.99721509e-01],
        [-2.74447719e-01],
        [-1.04138145e-01],
        [ 1.95097316e-01]])

### Now let's check this with actual output using library 

In [29]:
model = stm.OLS(y , X).fit()
model.params

array([-2.48065457e-16, -5.45402375e-01, -9.97800910e-02, -2.99721509e-01,
       -2.74447719e-01, -1.04138145e-01,  1.95097316e-01])

In [30]:
import numpy as np
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X, y)
reg.score(X, y)

print(reg.coef_)

print(reg.intercept_)



[[ 0.         -0.54540238 -0.09978009 -0.29972151 -0.27444772 -0.10413814
   0.19509732]]
[-3.45480152e-16]
